"""Contains all custom classes used throughout the jargen package"""
from ipaddress import IPv4Network

class Route:
    """Object representing a route generated by jargen"""
    def __init__(self, network: IPv4Network, aspath: list[str] = [], origin: str = "igp", communities: list[str] = []):
        self.network = network
        self.aspath = aspath
        self.origin = origin
        self.communities = communities

class Neighbor:
    """Object representing a BGP neighbor to be used in configuration generation"""
    def __init__(self, address: str, asn: int):
        self.address = address
        self.asn = asn

class Attribute:
    """Object representing a custom key:value attribute to be used in configuration generation"""
    def __init__(self, name: str, value: str):
        self.name = name
        self.value = value